<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Version>0.0.0.1</Version>
        <PackageProjectUrl>https://github.com/goatcorp/MSBT</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>  
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <PathMap>$(MSBuildProjectDirectory)=MSBT</PathMap>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\Data\goat.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Fonts\defused.ttf" />
    </ItemGroup>

</Project>